### ISSUE TITLE
Trojans detected by VirusTotal

### ISSUE THREAD

**Issue by TuneMeIn** [rickyrorton/spotify-downloader#12] opened 2022-08-21 07:14 UTC
Is there something that's triggering false positives because otherwise, this seems very sketchy.
![VirusTotal Scan](https://user-images.githubusercontent.com/107177248/185780055-4a6e19af-92e9-419a-9ab1-fb30e3cb3e0d.png)

**Comment by rickyrorton** [comment] 2022-08-21 09:37
I can assure there is no trojans or any other kind of malware in the code also there are only 6/70 detections which most like are false positives (and from some vendors which I've never heard of )probably due to how pyinstaller compiles the code into a executable.
Let me know if you want to compile the code yourself with the source code in the repository,I will be happy to help you out with that

**Comment by the-batfish** [comment] 2022-08-21 10:10
Also not to mention this is a duplicate of a previous issue that has already been closed as seen here https://github.com/rickyrorton/spotify-downloader/issues/8

**Comment by the-batfish** [comment] 2022-08-21 10:23
This is a duplicate of this already resolved issue. Here's the link https://github.com/rickyrorton/spotify-downloader/issues/8

**Comment by TuneMeIn** [comment] 2022-08-21 19:30
Oh ok, I was just skeptical since I've been hacked badly before but I appreciate you taking time to assure this is safe. I'm happy to run straight from executable, just needed to know it wouldn't steal my account passwords like an old virus I had haha. Have a great day 😉

**Comment by rickyrorton** [comment] 2022-08-22 02:32
Ah no issues even I am very skeptical of what i download some i have also been hacked in the past

**Closed as completed** 2022-08-22 02:32 UTC
